// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKctEQNotyQtAkIEacVzmsUuAjmTLqLQ',
    appId: '1:299236802444:web:5576ddafc31570794b60a9',
    messagingSenderId: '299236802444',
    projectId: 'wedding-app-a56df',
    authDomain: 'wedding-app-a56df.firebaseapp.com',
    storageBucket: 'wedding-app-a56df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LFQPni2fQl6VxaHA-JS0HUHHhQ_dGAo',
    appId: '1:299236802444:android:c2a5cc35151e72a34b60a9',
    messagingSenderId: '299236802444',
    projectId: 'wedding-app-a56df',
    storageBucket: 'wedding-app-a56df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-C-3I49P-O1WhU9FbCRsmRun5VU4hJ0',
    appId: '1:299236802444:ios:3c96fc857e7e22d84b60a9',
    messagingSenderId: '299236802444',
    projectId: 'wedding-app-a56df',
    storageBucket: 'wedding-app-a56df.firebasestorage.app',
    iosBundleId: 'com.example.weddinginviteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-C-3I49P-O1WhU9FbCRsmRun5VU4hJ0',
    appId: '1:299236802444:ios:3c96fc857e7e22d84b60a9',
    messagingSenderId: '299236802444',
    projectId: 'wedding-app-a56df',
    storageBucket: 'wedding-app-a56df.firebasestorage.app',
    iosBundleId: 'com.example.weddinginviteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMKctEQNotyQtAkIEacVzmsUuAjmTLqLQ',
    appId: '1:299236802444:web:edc9ec1ec62821914b60a9',
    messagingSenderId: '299236802444',
    projectId: 'wedding-app-a56df',
    authDomain: 'wedding-app-a56df.firebaseapp.com',
    storageBucket: 'wedding-app-a56df.firebasestorage.app',
  );

}